<a href="https://colab.research.google.com/github/Rupesh05/ML_Workshop---IIT-Kanpur/blob/main/Iris_Assignment_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import Iris Dataset

In [ ]:
import sklearn
from sklearn.datasets import load_iris
import numpy as np
import keras
np.random.seed(10)

iris = load_iris()

Using TensorFlow backend.


In [ ]:
#print type of iris 
type(iris)

sklearn.utils.Bunch

### Data Exploration

In [ ]:
## Print parent classes of this type
print(sklearn.utils.Bunch.__bases__)
#shape



(<class 'dict'>,)


So, you must have found that iris is a dict object

In [ ]:
## Print the keys present in iris
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [ ]:
## Create X and Y variables. X is the input features, Y is the output labels
X = iris['data']
Y = iris['target']
Y = np.array(Y).reshape(-1,1)
#print(Y)

In [ ]:
## Track 5 random samples
isamples = np.random.randint(len(X), size = (5))
print(isamples)

[  9 125  15  64 113]


In [ ]:
#Shape of Data
iris['data'].shape
# Print shapes of X and Y
print(X.shape)
print(Y.shape)

(150, 4)
(150, 1)


### Preprocess Data

#### Convert Labels(Y) to one-hot encoding 

In [ ]:
### Convert Y to 1-hot encoding
##Your Code Here
def oneHot(y,Ny):
   
    Y = np.zeros(Ny)
    Y[y] = 1
    return Y

Ny=3
Y = np.array([oneHot(y,Ny) for y in Y])
# Look at converted Y for the random samples we are tracking
print(Y[isamples])

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Its time to split your model into training and testing samples 

In [ ]:
### split the data into 80% training and 20% testing 
### Split X into two variables X_train and X_test
### Split Y correspondingly into two variables Y_train and Y_test

### Your Code Her
import pandas as pd
df = pd.DataFrame(X)
ef = pd.DataFrame(Y)
msk = np.random.rand(len(df)) <= 0.8
X_train = df[msk]
X_test = df[~msk]
Y_train = ef[msk]
Y_test = ef[~msk].values
#print(len(X_train),len(X_test),len(Y_train),len(Y_test))
#print(X_train)
#print(Y_train)
#print(X_train.shape)

### Data Normalization/Scaling


In [ ]:
### Normalize data to be of zero mean and unit variance
mean = np.sum(X_train, axis=0)/X_train.shape[0]
X1 = X_train - mean
stddev = np.sqrt(np.sum(X1*X1, axis=0)/X_train.shape[0])
#print(mean)
#print(stddev)
X_normalised = (X_train - mean)/(stddev+1e-8)
#print(X_normalised)

Note: If the first 5 samples of X_train and Y_train looks like the one given below
then congratulations! You are on the right track;
If not, then persistance is the key to success :)


In [ ]:
## Print and observe the normalized inputs and compare with older inputs
print(X_normalised,"normalise data ")
print(X_train,"Initial data ")

            0         1         2         3
0   -0.961097  1.066880 -1.384347 -1.366022
1   -1.208236 -0.110238 -1.384347 -1.366022
2   -1.455375  0.360609 -1.441350 -1.366022
3   -1.578944  0.125186 -1.327345 -1.366022
4   -1.084666  1.302303 -1.384347 -1.366022
5   -0.590388  2.008574 -1.213340 -1.100407
6   -1.578944  0.831456 -1.384347 -1.233214
7   -1.084666  0.831456 -1.327345 -1.366022
9   -1.208236  0.125186 -1.327345 -1.498830
10  -0.590388  1.537727 -1.327345 -1.366022
12  -1.331805 -0.110238 -1.384347 -1.498830
13  -1.949653 -0.110238 -1.555355 -1.498830
14  -0.096110  2.243998 -1.498352 -1.366022
16  -0.590388  2.008574 -1.441350 -1.100407
17  -0.961097  1.066880 -1.384347 -1.233214
18  -0.219679  1.773150 -1.213340 -1.233214
19  -0.961097  1.773150 -1.327345 -1.233214
20  -0.590388  0.831456 -1.213340 -1.366022
21  -0.961097  1.537727 -1.327345 -1.100407
22  -1.578944  1.302303 -1.612357 -1.366022
23  -0.961097  0.596033 -1.213340 -0.967599
24  -1.331805  0.831456 -1.09933

### Training time (using Neural Networks)

- create your NN model with given structure (4 input neurons, 8 hidden neurons and 3 output neurons)
- use 'relu' activation in hidden layer 
- use softmax activation in output
- Compile your model using 'categorical_crossentropy' loss function and sgd optimizer
- Track the accuracy metric of the model

In [ ]:
## Define the model
from keras.layers import Input, Dense
from keras.models import Model
from keras import optimizers
Nx = 4
x = Input(shape=(Nx,)) 

y = Dense(8, activation='relu')(x) 

y = Dense(3, activation='softmax')(y)
model = Model(inputs=x, outputs=y)
model.compile(optimizer=optimizers.sgd(lr=0.001), loss='categorical_crossentropy', metrics=['accuracy'])


Instructions for updating:
Colocations handled automatically by placer.


In [ ]:
## Print the model summary
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 4)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 27        
Total params: 67
Trainable params: 67
Non-trainable params: 0
_________________________________________________________________


In [ ]:
## Fit the model to data
model.fit(X_normalised, Y_train, epochs=50)

Epoch 1/50
126/126 [==============================] - 0s 74us/step - loss: 1.0120 - acc: 0.4127
Epoch 2/50
126/126 [==============================] - 0s 81us/step - loss: 1.0100 - acc: 0.4127
Epoch 3/50
126/126 [==============================] - 0s 82us/step - loss: 1.0081 - acc: 0.4127
Epoch 4/50
126/126 [==============================] - 0s 111us/step - loss: 1.0062 - acc: 0.4127
Epoch 5/50
126/126 [==============================] - 0s 98us/step - loss: 1.0043 - acc: 0.4127
Epoch 6/50
126/126 [==============================] - 0s 80us/step - loss: 1.0024 - acc: 0.4206
Epoch 7/50
126/126 [==============================] - 0s 64us/step - loss: 1.0005 - acc: 0.4206
Epoch 8/50
126/126 [==============================] - 0s 77us/step - loss: 0.9986 - acc: 0.4206
Epoch 9/50
126/126 [==============================] - 0s 80us/step - loss: 0.9967 - acc: 0.4286
Epoch 10/50
126/126 [==============================] - 0s 65us/step - loss: 0.9949 - acc: 0.4286
Epoch 11/50
126/126 [=================

In [ ]:
## Test the accuracy of the model on test data
history = model.fit(X_normalised, Y_train, epochs=50)

Epoch 1/50
126/126 [==============================] - 0s 72us/step - loss: 1.1282 - acc: 0.3254
Epoch 2/50
126/126 [==============================] - 0s 63us/step - loss: 1.1255 - acc: 0.3333
Epoch 3/50
126/126 [==============================] - 0s 50us/step - loss: 1.1227 - acc: 0.3413
Epoch 4/50
126/126 [==============================] - 0s 70us/step - loss: 1.1200 - acc: 0.3413
Epoch 5/50
126/126 [==============================] - 0s 63us/step - loss: 1.1173 - acc: 0.3413
Epoch 6/50
126/126 [==============================] - 0s 74us/step - loss: 1.1146 - acc: 0.3413
Epoch 7/50
126/126 [==============================] - 0s 69us/step - loss: 1.1119 - acc: 0.3413
Epoch 8/50
126/126 [==============================] - 0s 59us/step - loss: 1.1093 - acc: 0.3413
Epoch 9/50
126/126 [==============================] - 0s 50us/step - loss: 1.1066 - acc: 0.3413
Epoch 10/50
126/126 [==============================] - 0s 56us/step - loss: 1.1041 - acc: 0.3413
Epoch 11/50
126/126 [==================

### Confusion Matrix and Accuracy

In [ ]:
### Lastly, report the accuracy of your model and print the Confusion Matrix
from sklearn.metrics import confusion_matrix
loss, accuracy = model.evaluate(X_test, Y_test, verbose=0)  # Evaluate the model
print('Accuracy :%0.3f'%accuracy)
Y_pred = model.predict(X_test)
# Confusion Matrix

confusion_matrix(np.argmax(Y_test, axis=1), np.argmax(Y_pred, axis = 1 ))

Accuracy :0.208


array([[ 0,  0, 10],
       [ 0,  0,  9],
       [ 0,  0,  5]])